### ISSUE TITLE
Typo in shortcode folder on the readme page

### ISSUE THREAD

**Issue by ochapeau** [yuma-m/hugo-shortcodes-soundcloud#2]
Thank you for this useful shortcode!
I noticed that on the readme page it is written to place the html file in `/layouts/shortcode`, however, according to the hugo [documentation](https://gohugo.io/templates/shortcode-templates/) it should be put in `/layouts/shortcodes`.

**Comment by yuma-m** [comment]
Hi @ochapeau, thank you for your comment. I fixed it.
